print("Getting to know you!")
name = input("What is your name? ")
favfood = input("What's your favourite food? ")
favmusic = input("Which music you like to listen more oftenly? ")
place = input("Where do you live? ")
print("You are")
print(name)
print("You're probably hungry for ")
print(favfood)
print("and you're definitely getting your groove on to")
print(favmusic)
print("living in the amazing")
print(place)